# Generated by Django 3.2.5 on 2021-09-09 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, help_text='File shared in a conversation', null=True, upload_to='conversation/', verbose_name='Shared File')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'w3chat_chat_messages',
                'ordering': ['-created_on'],
                'get_latest_by': 'created_on',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('friendly_name', models.CharField(blank=True, max_length=64, null=True)),
                ('identifier_id', models.CharField(blank=True, max_length=32, null=True)),
                ('is_admin_conversation', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'w3chat_conversations',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('user_id', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'w3chat_participants',
            },
        ),
    ]
