# Generated by Django 3.2.5 on 2021-09-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_admin_conversation',
        ),
        migrations.AddField(
            model_name='participant',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
