# Generated by Django 3.2.7 on 2021-09-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210910_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='user_id',
            field=models.CharField(max_length=128),
        ),
    ]
