# Generated by Django 3.2.7 on 2021-10-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210929_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientoffensivewords',
            options={'verbose_name_plural': 'ClientOffensiveWords'},
        ),
        migrations.AlterModelOptions(
            name='clientreformats',
            options={'verbose_name_plural': 'ClientREFormats'},
        ),
        migrations.AddField(
            model_name='conversation',
            name='connected',
            field=models.ManyToManyField(related_name='connected_users', to='chat.Participant'),
        ),
        migrations.AlterField(
            model_name='offensiveword',
            name='word',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='reformat',
            name='expression',
            field=models.CharField(choices=[('p', 'Phone Number'), ('e', 'Email'), ('u', 'Url')], max_length=128, unique=True),
        ),
    ]
