# Generated by Django 3.2.7 on 2021-10-04 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20211003_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_from',
            field=models.ManyToManyField(to='chat.Participant'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_messages', to='chat.participant'),
        ),
        migrations.AlterField(
            model_name='reformat',
            name='expression',
            field=models.CharField(choices=[('^\\+?1?\\d{9,15}$', 'Phone Number'), ('^[a-z0-9]+[\\._]?[a-z0-9]+[@]\\w+[.]\\w{2,3}$', 'Email'), ('u', 'Url')], max_length=128, unique=True),
        ),
    ]
