# Generated by Django 3.2.7 on 2021-10-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20211004_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='count_connection',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
