# Generated by Django 3.2.7 on 2021-10-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_participant_count_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
