# Generated by Django 3.2.7 on 2021-10-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatmessage_is_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_for', to='chat.chatmessage'),
        ),
        migrations.CreateModel(
            name='FavoriteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(to='chat.ChatMessage')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='favorite_messages', to='chat.participant')),
            ],
            options={
                'db_table': 'w3chat_favorite_messages',
            },
        ),
    ]
