# Generated by Django 3.2.7 on 2021-10-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20211011_0630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'get_latest_by': 'created_on', 'ordering': ['-created_on'], 'verbose_name': 'Message'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('message', 'Message'), ('date', 'Date')], default='message', max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
