# Generated by Django 3.2.7 on 2021-10-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20211016_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='count_connection',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_online',
        ),
    ]
