# Generated by Django 3.2.7 on 2021-10-20 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20211019_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
    ]
