# Generated by Django 3.2.7 on 2021-10-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20211021_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='connected',
            field=models.ManyToManyField(related_name='connected_users', through='chat.ConnectedParticipantConversation', to='chat.Participant'),
        ),
    ]
